- hosts: all
  become: yes
  gather_facts: no
  tasks:
    - debug:
        var: cmd
    - shell:
        cmd: "{{ cmd }}"
      register: output
    - copy:
        dest: "{{ inventory_hostname }}.tmp"
        content: "{{ output.stdout }}"
      delegate_to: localhost
    # - ansible.utils.fact_diff:
    #     before: "{{ hostvars['RL89'].output.stdout }}"
    #     after: "{{ hostvars['RL93'].output.stdout }}"
    #   delegate_to: localhost
    #   run_once: true
